services:
  - type: web
    name: attendance-backend-api
    runtime: docker
    plan: starter
    region: oregon
    branch: main
    dockerfilePath: ./Dockerfile
    # Database initialization 
    preDeployCommand: python init_db.py
    envVars:
      - key: FLASK_SECRET
        generateValue: true
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: attendance-db
          property: connectionString
      - key: REDIS_URL
        value: ""
      - key: PORT
        value: "10000"
      - key: WORKERS
        value: "2"
      - key: THREADS
        value: "4"
      # Frontend URL - UPDATE THIS after deploying 
      - key: FRONTEND_URL
        value: "https://attendance-frontend-f94l.onrender.com"
      - key: PYTHON_VERSION
        value: "3.11"
      - key: TF_CPP_MIN_LOG_LEVEL
        value: "2"
      - key: FACE_THRESHOLD
        value: "0.6"
      - key: MIN_IMAGES
        value: "5"
      - key: LOG_LEVEL
        value: "INFO"
    healthCheckPath: /health
    autoDeploy: true

databases:
  # PostgreSQL Database
  - name: attendance-db
    databaseName: mydb
    user: attendance_user
    plan: starter
    region: oregon
    ipAllowList: []